name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
      max-parallel: 4

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Apply migrations (without tests)
      run: |
        python manage.py migrate --noinput

    - name: Run the server (optional check)
      run: |
        python manage.py runserver &
        sleep 10  # Wait for the server to start
        curl http://127.0.0.1:8000  # Make a simple request to ensure the server is running
